[project]
name = "census-getter"
version = "0.0.1"
description = "ACS Data to Pandas Dataframes"
authors = [
    {name = "PSRC", email = "scoe@psrc.org"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["activitysim==1.2.1",
    "numpy==1.26",
    "setuptools",
]
[tool.setuptools.packages.find]
where = ["census_getter"] # Tells setuptools to look in the 'src' folder
include = ["census_getter*"]

[project.scripts]
activitysim = "census_getter.cli.main:main"

